<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.Master" AutoEventWireup="true" CodeBehind="AdminViewRoom.aspx.cs" Inherits="hospital_management_system.AdminViewRoom" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div style="margin-top:10%;margin-left:35%">
    <form id="f1" runat="server">
    <asp:GridView ID="GridView1" runat="server" DataKeyNames="roomid" OnRowDataBound="OnRowDataBound" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateDeleteButton="true">
        <HeaderStyle CssClass="text-center" BackColor="WhiteSmoke" Height="50px" />
            <RowStyle  CssClass="text-center" Height="30px" Width="200px" />
            <FooterStyle BackColor="WhiteSmoke"/>
        <EmptyDataRowStyle CssClass="text-center"/>
        <EmptyDataTemplate>
            <asp:Label runat="server" ID="l1">No data found.!</asp:Label>
        </EmptyDataTemplate>
    </asp:GridView><br />
    <asp:Button ID="b1" runat="server" OnClick="add_click"  Text="Add New Room"/>
        </form>
        <//div>
</asp:Content>
